import type { MailFolder, MailMessage } from "./types";

export const testInboxFolderId = "acc_test:inbox:INBOX";

export const testFolders: MailFolder[] = [
  { id: testInboxFolderId, role: "inbox", name: "收件箱", unread: 2 },
  { id: "role:sent", role: "sent", name: "已发送", unread: 0 },
  { id: "role:drafts", role: "drafts", name: "草稿", unread: 0 },
  { id: "role:archive", role: "archive", name: "归档", unread: 0 },
  { id: "role:trash", role: "trash", name: "垃圾箱", unread: 0 },
];

export const testMessages: MailMessage[] = [
  {
    id: "1",
    accountId: "acc_test",
    folderId: testInboxFolderId,
    folderRole: "inbox",
    uid: 1,
    from: "sarah@stripe.com",
    fromName: "Sarah Chen",
    subject: "Q3 发布物料已就绪，请审阅",
    snippet: "Hey team, attached the final brand deck…",
    date: "今天 09:41",
    dateMs: Date.now(),
    unread: true,
    split: "important",
    html: "<p>Hey team,</p><p>Brand deck ready.</p>",
  },
  {
    id: "2",
    accountId: "acc_test",
    folderId: testInboxFolderId,
    folderRole: "inbox",
    uid: 2,
    from: "alex@lumen.soft",
    fromName: "Alex Rivera",
    subject: "定价页反馈",
    snippet: "新开关看起来好多了…",
    date: "昨天",
    dateMs: Date.now() - 86_400_000,
    unread: true,
    split: "important",
    html: "<p>新开关看起来好多了。</p>",
  },
  {
    id: "3",
    accountId: "acc_test",
    folderId: testInboxFolderId,
    folderRole: "inbox",
    uid: 3,
    from: "legal@acme.com",
    fromName: "Legal · Acme",
    subject: "合同签字提醒",
    snippet: "请在 EOD 前审阅…",
    date: "08:22",
    dateMs: Date.now() - 3_600_000,
    unread: false,
    split: "other",
    html: "<p>请审阅第 4.2 节。</p>",
  },
  {
    id: "4",
    accountId: "acc_test",
    folderId: testInboxFolderId,
    folderRole: "inbox",
    uid: 4,
    from: "bob@example.com",
    fromName: "Bob",
    subject: "会议纪要",
    snippet: "昨天会议要点如下…",
    date: "昨天",
    dateMs: Date.now() - 90_000_000,
    unread: false,
    split: "important",
    html: "<p>会议纪要</p>",
  },
];
